(function(g){var window=this;var Xpa=function(a,b){return g.Vb(a,b)},g5=function(){},Ypa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Zpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.z)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Ypa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},h5=function(a){g.Vm(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},i5=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.$m(a.l,b,c)},j5=function(a){return(a=g.to(a))?new ActiveXObject(a):new XMLHttpRequest},k5=function(a,b){return b+" ["+a.ba+" "+a.D+" "+a.getStatus()+"]"},$pa=function(a){return"content-type"==a.toLowerCase()},l5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},aqa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},m5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},n5=function(a,b){if(a.g){l5(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},o5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;m5(a);n5(a)},p5=function(a){return a.g?a.g.readyState:0},q5=function(a){if(a.i&&"undefined"!=typeof g.kY)if(a.P[1]&&4==p5(a)&&2==a.getStatus())k5(a,"Local request error detected and ignored");
else if(a.C&&4==p5(a))g.Gg(a.Zv,0,a);else if(a.dispatchEvent("readystatechange"),4==p5(a)){k5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!bqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<p5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";m5(a)}}finally{n5(a)}}},r5=function(a){g.Sf.call(this);
this.headers=new g.Km;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.D="";this.u=0;this.l="";this.o=this.V=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},s5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},cqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Io.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Ho(e)&&c.push(d):c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.z)(c,function(d){g.Io.prototype.remove.call(this,d)},a)},t5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},eqa=function(a,b){g.ab(a,b)||a.push(b)},u5=function(a){var b=0,c;
for(c in a)b++;return b},v5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},fqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.i=d);return e},w5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return fqa(a)},x5=function(){this.g=[];
this.i=[]},y5=function(a,b){g.Np[a]=!0;
var c=g.Lp();c&&c.publish.apply(c,arguments);g.Np[a]=!1},z5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",hqa(this,a.capabilities||""),iqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},hqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa(Xpa,jqa)).forEach(function(c){a.capabilities.add(c)})},iqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},A5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},B5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},C5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kqa=function(a){return new A5(a)},D5=function(a){return g.Ma(a)?(0,g.B)(a,kqa):[]},E5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},F5=function(a){return g.Ma(a)?"["+(0,g.B)(a,E5).join(",")+"]":"null"},G5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},H5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},I5=function(a,b){return g.Ya(a,function(c){return B5(c,b)})},J5=function(a){try{var b=(0,g.et)(),c=(0,g.dt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},mqa=function(){var a=(0,g.dt)();
a&&dqa(a,a.g.lf(!0))},K5=function(){var a=g.gt("yt-remote-connected-devices")||[];
g.rb(a);return a},nqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},L5=function(a){g.ft("yt-remote-connected-devices",a,86400)},N5=function(){if(M5)return M5;
var a=g.gt("yt-remote-device-id");a||(a=G5(),g.ft("yt-remote-device-id",a,31536E3));for(var b=K5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return M5=d},O5=function(){var a=K5(),b=N5();
g.ab(a,b);g.ht()&&g.tb(a,b);a=nqa(a);if(0==a.length)try{g.hs("remote_sid")}catch(c){}else try{g.gs("remote_sid",a.join(","),-1)}catch(c){}},P5=function(){return g.gt("yt-remote-session-browser-channel")},Q5=function(){return g.gt("yt-remote-local-screens")||[]},R5=function(){g.ft("yt-remote-lounge-token-expiration",!0,86400)},oqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(Q5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&R5();
g.ft("yt-remote-local-screens",a,31536E3)},pqa=function(a,b){g.ft("yt-remote-session-browser-channel",a);
g.ft("yt-remote-session-screen-id",b);var c=K5(),d=N5();g.ab(c,d)||c.push(d);L5(c);O5()},S5=function(a){a||(J5("yt-remote-session-screen-id"),J5("yt-remote-session-video-id"));
O5();a=K5();g.db(a,N5());L5(a)},U5=function(){if(!T5){var a=g.So();
a&&(T5=new g.Co(a))}return T5?!!T5.get("yt-remote-use-staging-server"):!1},V5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},W5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Y5=function(a){a.length?X5(a.shift(),function(){Y5(a)}):Z5()},qqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},X5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Z5=function(){var a=W5();
a&&a(!1,"No cast extension found")},$5=function(){if(rqa){var a=2,b=W5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;X5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Z5,c)}},sqa=function(){$5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Y5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},a6=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Wc=b;this.u=(0,g.x)(this.lD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},b6=function(){},c6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.an(this);this.i=new g.Fg;this.i.setInterval(250)},e6=function(a,b,c){a.Yh=1;
a.Zf=h5(b.clone());a.uh=c;a.u=!0;d6(a,null)},f6=function(a,b,c,d,e){a.Yh=1;
a.Zf=h5(b.clone());a.uh=null;a.u=c;e&&(a.Vz=!1);d6(a,d)},d6=function(a,b){a.Hi=(0,g.H)();
g6(a);a.Gg=a.Zf.clone();i5(a.Gg,"t",a.A);a.fl=0;a.tc=a.g.np(a.g.Rk()?b:null);0<a.Sp&&(a.Hn=new g.Al((0,g.x)(a.cB,a,a.tc),a.Sp));a.aa.ca(a.tc,"readystatechange",a.dM);var c=a.bh?g.cc(a.bh):{};a.uh?(a.no="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Gg,a.no,a.uh,c)):(a.no="GET",a.Vz&&!g.Od&&(c.Connection="close"),a.tc.send(a.Gg,a.no,null,c));a.g.te(1)},n6=function(a,b,c){for(var d=!0;!a.Rg&&a.fl<c.length;){var e=tqa(a,c);
if(e==h6){4==b&&(a.rg=4,i6(15),d=!1);break}else if(e==j6){a.rg=4;i6(16);d=!1;break}else k6(a,e)}4==b&&0==c.length&&(a.rg=1,i6(17),d=!1);a.xe=a.xe&&d;d||(l6(a),m6(a))},tqa=function(a,b){var c=a.fl,d=b.indexOf("\n",c);
if(-1==d)return h6;c=Number(b.substring(c,d));if(isNaN(c))return j6;d+=1;if(d+c>b.length)return h6;var e=b.substr(d,c);a.fl=d+c;return e},q6=function(a,b){a.Hi=(0,g.H)();
g6(a);var c=b?window.location.hostname:"";a.Gg=a.Zf.clone();g.Vm(a.Gg,"DOMAIN",c);g.Vm(a.Gg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){l6(a);a.rg=7;i6(22);m6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in o6)k=o6[l];else if(l in p6)k=o6[l]=p6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
o6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Nc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.uL,a);a.Be.parentWindow.d=(0,g.x)(a.Zy,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.Zy,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Dc(a.Gg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},g6=function(a){a.Xs=(0,g.H)()+a.o;
r6(a,a.o)},r6=function(a,b){if(null!=a.Yi)throw Error("WatchDog timer not null");
a.Yi=s6((0,g.x)(a.EL,a),b)},t6=function(a){a.Yi&&(g.v.clearTimeout(a.Yi),a.Yi=null)},m6=function(a){a.g.Xv()||a.Rg||a.g.un(a)},l6=function(a){t6(a);
g.qf(a.Hn);a.Hn=null;a.i.stop();g.cn(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},k6=function(a,b){try{a.g.Ty(a,b),a.g.te(4)}catch(c){}},v6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;u6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){v6(a,b,c,d,f)},f)})}},u6=function(a,b,c){var d=new Image;
d.onload=function(){try{w6(d),c(!0)}catch(e){}};
d.onerror=function(){try{w6(d),c(!1)}catch(e){}};
d.onabort=function(){try{w6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{w6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
v5(d,a)},w6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},x6=function(a){this.g=a;
this.i=new b6},z6=function(a){var b=y6(a.g,a.kj,"/mail/images/cleardot.gif");
h5(b);v6(b.toString(),5E3,(0,g.x)(a.rC,a),3,2E3);a.te(1)},B6=function(a){var b=a.g.F;
if(null!=b)i6(5),b?(i6(11),A6(a.g,a,!1)):(i6(12),A6(a.g,a,!0));else if(a.Cd=new c6(a,void 0,void 0,void 0),a.Cd.bh=a.Qp,b=a.g,b=y6(b,b.Rk()?a.Sj:null,a.Rp),i6(5),!g.Md||g.pd(10))i5(b,"TYPE","xmlhttp"),f6(a.Cd,b,!1,a.Sj,!1);else{i5(b,"TYPE","html");var c=a.Cd;a=!!a.Sj;c.Yh=3;c.Zf=h5(b.clone());q6(c,a)}},C6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new b6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},uqa=function(a,b){this.g=a;
this.map=b;this.context=null},D6=function(a){g.sf.call(this,"statevent",a)},E6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},F6=function(a){g.sf.call(this,"serverreachability",a)},J6=function(a){G6(a);
if(3==a.g){var b=a.zk++,c=a.gm.clone();g.Vm(c,"SID",a.l);g.Vm(c,"RID",b);g.Vm(c,"TYPE","terminate");H6(a,c);b=new c6(a,a.l,b,void 0);b.Yh=2;b.Zf=h5(c.clone());v5(new Image,b.Zf.toString());b.Hi=(0,g.H)();g6(b)}I6(a)},L6=function(a){a.KC(1,0);
a.gm=y6(a,null,a.Pp);K6(a)},G6=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.nf&&(g.v.clearTimeout(a.nf),a.nf=null);M6(a);a.yd&&(a.yd.cancel(),a.yd=null);a.ng&&(g.v.clearTimeout(a.ng),a.ng=null)},N6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new uqa(a.JH++,b));2!=a.g&&3!=a.g||K6(a)},K6=function(a){a.yd||a.ng||(a.ng=s6((0,g.x)(a.Yy,a),0),a.Sh=0)},Q6=function(a,b){if(1==a.g){if(!b){a.zk=Math.floor(1E5*Math.random());
var c=a.zk++,d=new c6(a,"",c,void 0);d.bh=null;var e=O6(a),f=a.gm.clone();g.Vm(f,"RID",c);g.Vm(f,"CVER","1");H6(a,f);e6(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?P6(a,b):0==a.i.length||a.yd||P6(a))},P6=function(a,b){if(b)if(6<a.Sg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.zk-1;var d=O6(a)}else c=b.C,d=b.uh;else c=a.zk++,d=O6(a);var e=a.gm.clone();g.Vm(e,"SID",a.l);g.Vm(e,"RID",c);g.Vm(e,"AID",a.li);H6(a,e);c=new c6(a,a.l,c,a.Sh+1);c.bh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;e6(c,e,d)},H6=function(a,b){if(a.Tc){var c=a.Tc.zv();
c&&g.Lb(c,function(d,e){g.Vm(b,e,d)})}},O6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Sg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Sg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},R6=function(a){a.Sb||a.nf||(a.C=1,a.nf=s6((0,g.x)(a.Xy,a),0),a.Kh=0)},T6=function(a){if(a.Sb||a.nf||3<=a.Kh)return!1;
a.C++;a.nf=s6((0,g.x)(a.Xy,a),S6(a,a.Kh));a.Kh++;return!0},A6=function(a,b,c){a.ko=c;
a.Ie=b.Bf;a.A||L6(a)},M6=function(a){null!=a.Wg&&(g.v.clearTimeout(a.Wg),a.Wg=null)},S6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},V6=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.IM,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),h5(c));u6(c.toString(),1E4,d)}else i6(2);U6(a,b)},U6=function(a,b){a.g=0;
a.Tc&&a.Tc.Bu(b);I6(a);G6(a)},I6=function(a){a.g=0;
a.Ie=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.bp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Tc.bp(b)}},y6=function(a,b,c){var d=g.Wm(c);
if(""!=d.g)b&&g.Pm(d,b+"."+d.g),g.Qm(d,d.u);else{var e=window.location;d=gqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.xj&&g.Lb(a.xj,function(f,k){g.Vm(d,k,f)});
g.Vm(d,"VER",a.Sg);H6(a,d);return d},s6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},i6=function(a){W6.dispatchEvent(new D6(W6,a))},X6=function(){},vqa=function(a,b){this.action=a;
this.params=b||{}},Y6=function(a,b){g.D.call(this);
this.g=new g.M(this.mL,0,this);g.G(this,this.g);this.Wc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},Z6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Bo;this.i=new Y6(this.mM,this);this.g=null;this.fb=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},wqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ko,sessionId:a.g.l,arrayId:a.g.li}},$6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Q6(a.g),J6(a.g));a.D=0},a7=function(a){return!!a.g&&3==a.g.g},xqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},b7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},c7=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},d7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),ie:g.Sa(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fq(b,a)},yqa=function(){var a=e7;
f7();g7.push(a);h7(g7)},i7=function(a,b){f7();
var c=g7,d=zqa(a,String(b));0==c.length?Aqa(d):(h7(c),(0,g.z)(c,function(e){e(d)}))},f7=function(){g7||(g7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",g7,void 0))},Aqa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},h7=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},zqa=function(a,b){var c=((0,g.H)()-Bqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.P.call(this);
this.C=a;this.g=[]},n7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!H5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=n7(a,b[d])||c;return c},Dqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},o7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},q7=function(a){m7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;p7(this);this.info("Initializing with "+F5(this.g))},r7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=c7(a.l,"/pairing/get_lounge_token_batch");
d7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.vD,a),(0,g.x)(a.uD,a))}},p7=function(a){var b=D5(Q5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Cqa(a,b)},s7=function(a,b){oqa((0,g.B)(a.g,C5));
b&&R5()},u7=function(a,b){g.P.call(this);
this.A=b;var c=g.gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;t7("Initialized with "+g.Kg(this.g))},v7=function(a,b,c){var d=c7(a.u,"/pairing/get_screen_availability");
d7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},w7=function(a,b){a:if(u5(b)!=u5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));Eqa(a)},x7=function(a){isNaN(a.l)||g.Kp(a.l);
a.l=g.Ip((0,g.x)(a.Yr,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},t7=function(a){i7("OnlineScreenService",a)},y7=function(a){var b={};
(0,g.z)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Eqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.ft("yt-remote-online-screen-ids",a.join(","),60):J5("yt-remote-online-screen-ids")},z7=function(a){m7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Fqa(this)},B7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Hd();if(k=(c?I5(k,c):null)||I5(k,b)){k.uuid=b;var l=A7(a,k);v7(a.i,l,function(m){e(m?l:null)})}else c?Gqa(a,c,(0,g.x)(function(m){var n=A7(this,new A5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));v7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},C7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Gqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fq(c7(a.A,"/pairing/get_lounge_token_batch"),e)},D7=function(a){a.g=a.l.Hd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F5(a.g))},Fqa=function(a){E7(a);
a.l=new q7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.DD,a));D7(a);a.o=D5(g.gt("yt-remote-automatic-screen-cache")||[]);E7(a);a.info("Initializing automatic screens: "+F5(a.o));a.i=new u7(a.A,(0,g.x)(a.Hd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},A7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ft("yt-remote-automatic-screen-cache",(0,g.B)(a.o,C5)));E7(a);a.u[b.uuid]=b.id;g.ft("yt-remote-device-id-map",a.u,31536E3);return b},E7=function(a){a.u=g.gt("yt-remote-device-id-map")||{}},F7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},G7=function(a,b){i7(a.P,b)},I7=function(a,b){F7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.nN,this);this.u=(0,g.x)(this.PL,this);this.o=g.Ip((0,g.x)(function(){H7(this,null)},this),12E4)},Hqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){G7(this,"Failed to send message: getMdxSessionStatus.")},a)):G7(a,"Sending yt message without session: "+g.Kg(b))},H7=function(a,b){g.Kp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.wn,a),d=(0,g.x)(a.Kd,a);a.Pv(b,c,d,5)}}else a.Kd(Error("Waiting for session status timed out."))},J7=function(a,b,c){F7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.qN,this);this.g=g.Ja},K7=function(a){a.g=a.F.hB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.wn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Kd(b)},a))},L7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}U5()&&(b.env_useStageMdx=1);return g.ah(b)},M7=function(a,b){F7.call(this,a,b,"ManualSession");
this.g=g.Ip((0,g.x)(this.ni,this,null),150)},N7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.vK,this)},O7=function(a,b){return b?g.Ya(a.l,function(c){return B5(b,c.label)},a):null},P7=function(a){i7("Controller",a)},e7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},Q7=function(a){return a.u||!!a.l.length||!!a.g},R7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Wy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ni(null)):a.N("yt-remote-cast2-session-change",null))},S7=function(a){var b=a.i.gB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&B5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=O7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lqa=function(a,b,c,d,e,f,k){Iqa()?Jqa(b,e,f,k)&&(U7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?V7(a,c):(window.__onGCastApiAvailable=function(l,m){l?V7(a,c):(W7("Failed to load cast API: "+m),X7(!1),U7(!1),J5("yt-remote-cast-available"),J5("yt-remote-cast-receiver"),Y7(),c(!1))},d?g.Vp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?sqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Z5():($5(),Y5(Kqa.map(qqa))))):T7("Cannot initialize because not running Chrome")},Y7=function(){T7("dispose");
var a=Z7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);$7(!1);g.Qp(a8);a8.length=0},b8=function(){return!!g.gt("yt-remote-cast-installed")},c8=function(){var a=g.gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},d8=function(){T7("clearCurrentReceiver");
J5("yt-remote-cast-receiver")},e8=function(){return b8()?Z7()?Z7().getCastSession():(W7("getCastSelector: Cast is not initialized."),null):(W7("getCastSelector: Cast API is not installed!"),null)},g8=function(){b8()?Z7()?f8()?(T7("Requesting cast selector."),Z7().requestSession()):(T7("Wait for cast API to be ready to request the session."),a8.push(g.Pp("yt-remote-cast2-api-ready",g8))):W7("requestCastSelector: Cast is not initialized."):W7("requestCastSelector: Cast API is not installed!")},h8=function(a,
b){f8()?Z7().setConnectedScreenStatus(a,b):W7("setConnectedScreenStatus called before ready.")},Iqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ow||a},Mqa=function(a,b){Z7().init(a,b)},Jqa=function(a,b,c,d){var e=!1;
Z7()||(a=new N7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ft("yt-remote-cast-available",f);y5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){T7("onReceiverSelected: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f);y5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){T7("onReceiverResumed: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){T7("onSessionChange: "+E5(f));
f||J5("yt-remote-cast-receiver");y5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
T7("cloudview.createSingleton_: "+e);return e},Z7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},V7=function(a,b){X7(!0);
U7(!1);Mqa(a,function(c){c?($7(!0),g.Sp("yt-remote-cast2-api-ready")):(W7("Failed to initialize cast API."),X7(!1),J5("yt-remote-cast-available"),J5("yt-remote-cast-receiver"),Y7());b(c)})},T7=function(a){i7("cloudview",a)},W7=function(a){i7("cloudview",a)},X7=function(a){T7("setCastInstalled_ "+a);
g.ft("yt-remote-cast-installed",a)},f8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},$7=function(a){T7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},U7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},i8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Je=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},j8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},k8=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},l8=function(a,b){a.C=b;
a.A=(0,g.H)()},m8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},n8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&j8(a)},o8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},r8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new x5;this.l=this.i=null;this.F=(0,g.x)(this.rI,this);this.C=(0,g.x)(this.Ck,this);this.D=(0,g.x)(this.qI,this);this.H=(0,g.x)(this.FI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ct,this),p8(this))):c=3;0!=c&&(b?this.ct(c):g.Ip((0,g.x)(function(){this.ct(c)},this),0));
var d=e8();d&&q8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},s8=function(a){return new i8(a.o.getPlayerContextData())},p8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.sK,b),this))},a)},t8=function(a){(0,g.z)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},u8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},w8=function(a,b,c){var d=s8(a);
l8(d,c);-1E3!=d.playerState&&(d.playerState=b);v8(a,d)},x8=function(a,b,c){a.o.sendMessage(b,c)},v8=function(a,b){t8(a);
a.o.setPlayerContextData(o8(b));p8(a)},q8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ck(null));
a.l=b;a.l&&(i7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ck(a.l.media[0]))},y8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=s8(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;l8(d,a.i.getEstimatedTime());v8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},z8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),x8(this,b,c))},a)},A8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.Nr(window,"beforeunload",(0,g.x)(this.oD,this)));this.i=[];this.Oa=new i8;this.M=b.id;this.g=Nqa(this,c);this.g.subscribe("handlerOpened",this.vI,this);this.g.subscribe("handlerClosed",this.sI,this);this.g.subscribe("handlerError",this.tI,this);this.g.subscribe("handlerMessage",this.uI,this);xqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.ht()&&g.ft("yt-remote-session-video-id",d)},this)},B8=function(a){i7("conn",a)},Nqa=function(a,b){return new Z6(c7(a.O,"/bc"),b)},C8=function(a,b){a.N("proxyStateChange",b)},Oqa=function(a){a.u=g.Ip((0,g.x)(function(){B8("Connecting timeout");
this.Oh(1)},a),2E4)},D8=function(a){g.Kp(a.u);
a.u=NaN},E8=function(a){g.Kp(a.H);
a.H=NaN},Pqa=function(a){F8(a);
a.F=g.Ip((0,g.x)(function(){G8(this,"getNowPlaying")},a),2E4)},F8=function(a){g.Kp(a.F);
a.F=NaN},I8=function(a,b){b&&(D8(a),E8(a));
b==(a7(a.g)&&isNaN(a.u))?b&&(C8(a,1),G8(a,"getSubtitlesTrack")):b?(a.Mv()&&a.Oa.reset(),C8(a,1),G8(a,"getNowPlaying"),H8(a)):a.Oh(1)},Qqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},J8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;n8(a.Oa,c,d);a.N("remoteQueueChange")},Rqa=function(a,b){b.params=b.params||{};
J8(a,b);K8(a,b);a.N("autoplayDismissed")},K8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
l8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Pqa(a):F8(a);a.N("remotePlayerChange")},Sqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);l8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Tqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Uqa=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Vqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Je="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},H8=function(a){g.Kp(a.D);
a.D=g.Ip((0,g.x)(a.Oh,a,1),864E5)},G8=function(a,b,c){c?B8("Sending: action="+b+", params="+g.Kg(c)):B8("Sending: action="+b);
a.g.sendMessage(b,c)},L8=function(a){m7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.x)(this.lN,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.x)(this.WJ,this)))},$qa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ap("MDX_CONFIG")||b;mqa();O5();M8||(M8=new b7(b?b.loungeApiHost:void 0),U5()&&(M8.g="/api/loungedev"));N8||(N8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",N8,void 0));Wqa();var c=O8();if(!c){var d=new z7(M8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=O8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lqa(a,d,function(m){m?P8()&&h8(P8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){y5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),Q8("Initializing: "+g.Kg(b)),R8.push(g.Pp("yt-remote-cast2-availability-change",function(){y5("yt-remote-receiver-availability-change")})),R8.push(g.Pp("yt-remote-cast2-receiver-selected",function(){S8(null);
y5("yt-remote-auto-connect","cast-selector-receiver")})),R8.push(g.Pp("yt-remote-cast2-receiver-resumed",function(){y5("yt-remote-receiver-resumed","cast-selector-receiver")})),R8.push(g.Pp("yt-remote-cast2-session-change",Xqa)),R8.push(g.Pp("yt-remote-connection-change",function(m){m?h8(P8(),"YouTube TV"):T8()||(h8(null,null),d8())})),a=U8(),b.isAuto&&(a.id+="#dial"),g.wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),Q8(" -- with channel params: "+
g.Kg(a)),Yqa(a),c.start(),P8()||Zqa())},ara=function(){var a=V8();
b8()&&g.gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},V8=function(){var a=O8().Vc.$_gos();
var b=W8();b&&X8()&&(H5(a,b)||a.push(b));return lqa(a)},Y8=function(){var a=bra();
!a&&b8()&&c8()&&(a={key:"cast-selector-receiver",name:c8()});return a},bra=function(){var a=V8(),b=W8();
b||(b=T8());return g.Ya(a,function(c){return b&&B5(b,c.key)?!0:!1})},W8=function(){var a=P8();
if(!a)return null;var b=O8().Hd();return I5(b,a)},Xqa=function(a){Q8("remote.onCastSessionChange_: "+E5(a));
if(a){var b=W8();b&&b.id==a.id?h8(b.id,"YouTube TV"):(b&&Z8(),$8(a,1))}else X8()&&Z8()},Z8=function(){f8()?Z7().stopSession():W7("stopSession called before API ready.");
var a=X8();a&&(a.disconnect(1),a9(null))},b9=function(){var a=X8();
return!!a&&3!=a.getProxyState()},Q8=function(a){i7("remote",a)},O8=function(){if(!c9){var a=g.w("yt.mdx.remote.screenService_");
c9=a?new L8(a):null}return c9},P8=function(){return g.w("yt.mdx.remote.currentScreenId_")},d9=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},e9=function(){return g.w("yt.mdx.remote.connectData_")},S8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},X8=function(){return g.w("yt.mdx.remote.connection_")},a9=function(a){var b=X8();
S8(null);a||d9("");g.Ia("yt.mdx.remote.connection_",a,void 0);N8&&((0,g.z)(N8,function(c){c(a)}),N8.length=0);
b&&!a?y5("yt-remote-connection-change",!1):!b&&a&&y5("yt-remote-connection-change",!0)},T8=function(){var a=g.ht();
if(!a)return null;var b=O8().Hd();return I5(b,a)},$8=function(a,b){W8()&&W8();
if(f9)g9=a;else{d9(a.id);var c=new A8(M8,a,U8());c.connect(b,e9());c.subscribe("beforeDisconnect",function(d){y5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){X8()&&a9(null)});
a9(c)}},Zqa=function(){var a=T8();
a?(Q8("Resume connection to: "+E5(a)),$8(a,0)):(S5(),d8(),Q8("Skipping connecting because no session screen found."))},Wqa=function(){var a=U8();
if(g.Yb(a)){a=N5();var b=g.gt("yt-remote-session-name")||"",c=g.gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},U8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Yqa=function(a){a?(g.ft("yt-remote-session-app",a.app),g.ft("yt-remote-session-name",a.name)):(J5("yt-remote-session-app"),J5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},h9=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.rs(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.qJ);this.l.K(b,"captionschanged",this.pI);this.l.K(b,"captionssettingschanged",this.vA);this.l.K(b,"videoplayerreset",this.xn);this.l.K(b,"mdxautoplaycancel",this.qC);this.O=this.l.K(b,"onVolumeChange",this.Hy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Sy,this);c.subscribe("remotePlayerChange",this.Ek,this);c.subscribe("remoteQueueChange",this.xn,this);c.subscribe("autoplayUpNext",this.vy,
this);c.subscribe("previousNextChange",this.Py,this);c.subscribe("nowAutoplaying",this.Ly,this);c.subscribe("autoplayDismissed",this.uy,this);this.suggestion=null;this.F=new g.iC(64);this.o=new g.M(this.tA,500,this);g.G(this,this.o);this.A=new g.M(this.uA,1E3,this);g.G(this,this.A);this.I=new a6(this.SM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.TA,1E3,this);g.G(this,this.P);this.H=new g.Al(this.MF,1E3,this);g.G(this,this.H);this.M=g.Ja;this.vA();this.xn();this.Ek()},i9=function(a,b){a.u.Kc(b,
a.i.getVideoData().lengthSeconds)},k9=function(a){i9(a,0);
a.o.stop();j9(a,new g.iC(64))},m9=function(a,b){if(l9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.iA(a.i.getVideoData(1).videoId,c);a.C=s8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Ef,t5(c));j9(a,new g.iC(1))},o9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{HQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return s8(a.g).videoId==a.i.getVideoData(1).videoId},j9=function(a,b){a.A.stop();
var c=a.F;if(!g.oC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.aK(a.i,d);a.F=b;p9(a.u,c,b)}},q9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",T:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",T:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"Cancel"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
T:"Confirm"}]}]}]});this.l=new g.WP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},s9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.lP()]},{B:"div",G:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.WP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);r9(this,g.XJ(a))},r9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.jN("Error on $RECEIVER_NAME",c):g.pC(b)||g.U(b,4)?g.jN("Playing on $RECEIVER_NAME",c):g.jN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},t9=function(a,b){g.GT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},u9=function(a){g.zK.call(this,a);
this.i={key:G5(),name:"This computer"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.mk=new g.iC(64);this.H=0;this.Km=-1;if(!g.Oy(g.X(this.player))){a=this.player;var b=g.cD(a);b&&(b=b.dn())&&(b=new t9(a,b),g.G(this,b));b=new s9(a);g.G(this,b);g.lK(a,b.element,4);this.F=new q9;g.G(this,this.F);g.lK(a,this.F.element,4);this.D=!!T8()}},p9=function(a,b,c){a.mk=c;
a.player.N("presentingplayerstatechange",new g.tD(c,b))},v9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)Z8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.Ap("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Ap("SESSION_INDEX")||g.Ap("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),X8()||(f9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Ef,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=t5(c))&&(d.locationInfo=c);c=d}else c=null;Q8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(S8(c||null),f8()?Z7().setLaunchParams(c||null):W7("setLaunchParams called before ready.")):!c&&b9()&&P8()==b.key?y5("yt-remote-connection-change",!0):(Z8(),S8(c||null),c=O8().Hd(),(c=I5(c,b.key))&&$8(c,1))}},bqa=/^https?$/i,cra=["POST",
"PUT"];g.y(r5,g.Sf);g.h=r5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?j5(this.M):j5(g.HY);this.P=this.M?this.M.getOptions():g.HY.getOptions();this.g.onreadystatechange=(0,g.x)(this.Zv,this);try{g5(k5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){g5(k5(this,"Error opening Xhr: "+f.message));o5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Zpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Gd(),$pa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(cra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{l5(this),0<this.A&&(this.I=aqa(this.g),g5(k5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.bw,this)):this.F=g.Gg(this.bw,this.A,this)),g5(k5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){g5(k5(this,"Send error: "+f.message)),o5(this,f)}};
g.h.bw=function(){"undefined"!=typeof g.kY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,k5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(k5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),n5(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),n5(this,!0));r5.Xa.U.call(this)};
g.h.Zv=function(){this.ea()||(this.V||this.C||this.o?q5(this):this.uK())};
g.h.uK=function(){q5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<p5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var p6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},o6={"'":"\\'"},dra={};g.h=x5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Lma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var jqa={JN:"atp",VP:"ska",KP:"que",jP:"mus",UP:"sus",AO:"dsp",RP:"seq"};z5.prototype.jg=function(){var a=new z5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var T5,M5="",rqa=V5("loadCastFramework")||V5("loadCastApplicationFramework"),Kqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(a6,g.D);g.h=a6.prototype;g.h.kD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Wc:this.za=g.Gg(this.u,this.Wc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();a6.Xa.U.call(this)};
g.h.lD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};b6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
b6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=c6.prototype;g.h.bh=null;g.h.xe=!1;g.h.Yi=null;g.h.Xs=null;g.h.Hi=null;g.h.Yh=null;g.h.Zf=null;g.h.Gg=null;g.h.uh=null;g.h.tc=null;g.h.fl=0;g.h.Be=null;g.h.no=null;g.h.rg=null;g.h.Tj=-1;g.h.Vz=!0;g.h.Rg=!1;g.h.Sp=0;g.h.Hn=null;var j6={},h6={};g.h=c6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.dM=function(a){a=a.target;var b=this.Hn;b&&3==p5(a)?b.Pj():this.cB(a)};
g.h.cB=function(a){try{if(a==this.tc)a:{var b=p5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!s5(this.tc))break a;this.Rg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));t6(this);var e=this.tc.getStatus();this.Tj=e;var f=s5(this.tc);(this.xe=200==e)?(4==b&&l6(this),this.u?(n6(this,b,f),g.Ch&&this.xe&&3==b&&(this.aa.ca(this.i,"tick",this.WL),this.i.start())):k6(this,f),this.xe&&!this.Rg&&(4==b?this.g.un(this):(this.xe=
!1,g6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rg=3,i6(13)):(this.rg=0,i6(14)),l6(this),m6(this))}}catch(k){this.tc&&s5(this.tc)}finally{}};
g.h.WL=function(){var a=p5(this.tc),b=s5(this.tc);this.fl<b.length&&(t6(this),n6(this,a,b),this.xe&&4!=a&&g6(this))};
g.h.uL=function(a){s6((0,g.x)(this.tL,this,a),0)};
g.h.tL=function(a){this.Rg||(t6(this),k6(this,a),g6(this))};
g.h.Zy=function(a){s6((0,g.x)(this.sL,this,a),0)};
g.h.sL=function(a){this.Rg||(l6(this),this.xe=a,this.g.un(this),this.g.te(4))};
g.h.cancel=function(){this.Rg=!0;l6(this)};
g.h.EL=function(){this.Yi=null;var a=(0,g.H)();0<=a-this.Xs?(2!=this.Yh&&this.g.te(3),l6(this),this.rg=2,i6(18),m6(this)):r6(this,this.Xs-a)};
g.h.getLastError=function(){return this.rg};g.h=x6.prototype;g.h.Qp=null;g.h.Cd=null;g.h.In=!1;g.h.Yv=null;g.h.dm=null;g.h.Eq=null;g.h.Rp=null;g.h.ce=null;g.h.Bf=-1;g.h.Sj=null;g.h.kj=null;g.h.connect=function(a){this.Rp=a;a=y6(this.g,null,this.Rp);i6(3);this.Yv=(0,g.H)();var b=this.g.D;null!=b?(this.Sj=b[0],(this.kj=b[1])?(this.ce=1,z6(this)):(this.ce=2,B6(this))):(i5(a,"MODE","init"),this.Cd=new c6(this,void 0,void 0,void 0),this.Cd.bh=this.Qp,f6(this.Cd,a,!1,null,!0),this.ce=0)};
g.h.rC=function(a){if(a)this.ce=2,B6(this);else{i6(4);var b=this.g;b.Ie=b.hg.Bf;V6(b,9)}a&&this.te(2)};
g.h.np=function(a){return this.g.np(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.Bf=-1};
g.h.Xv=function(){return!1};
g.h.Ty=function(a,b){this.Bf=a.Tj;if(0==this.ce)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ie=this.Bf;V6(c,2);return}this.Sj=c[0];this.kj=c[1]}else c=this.g,c.Ie=this.Bf,V6(c,2);else if(2==this.ce)if(this.In)i6(7),this.Eq=(0,g.H)();else if("11111"==b){if(i6(6),this.In=!0,this.dm=(0,g.H)(),c=this.dm-this.Yv,!g.Md||g.pd(10)||500>c)this.Bf=200,this.Cd.cancel(),i6(12),A6(this.g,this,!0)}else i6(8),this.dm=this.Eq=(0,g.H)(),this.In=!1};
g.h.un=function(){this.Bf=this.Cd.Tj;if(this.Cd.xe)0==this.ce?this.kj?(this.ce=1,z6(this)):(this.ce=2,B6(this)):2==this.ce&&((!g.Md||g.pd(10)?!this.In:200>this.Eq-this.dm)?(i6(11),A6(this.g,this,!1)):(i6(12),A6(this.g,this,!0)));else{0==this.ce?i6(9):2==this.ce&&i6(10);var a=this.g;this.Cd.getLastError();a.Ie=this.Bf;V6(a,2)}};
g.h.Rk=function(){return this.g.Rk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=C6.prototype;g.h.xj=null;g.h.yd=null;g.h.Sb=null;g.h.Pp=null;g.h.gm=null;g.h.pu=null;g.h.rm=null;g.h.zk=0;g.h.JH=0;g.h.Tc=null;g.h.ng=null;g.h.nf=null;g.h.Wg=null;g.h.hg=null;g.h.ko=null;g.h.li=-1;g.h.Gw=-1;g.h.Ie=-1;g.h.Sh=0;g.h.Kh=0;g.h.Sg=8;var W6=new g.Sf;g.y(D6,g.sf);g.y(E6,g.sf);g.y(F6,g.sf);g.h=C6.prototype;g.h.connect=function(a,b,c,d,e){i6(0);this.Pp=b;this.xj=c||{};d&&g.Ea(e)&&(this.xj.OSID=d,this.xj.OAID=e);this.A?(s6((0,g.x)(this.Ju,this,a),100),L6(this)):this.Ju(a)};
g.h.Ju=function(a){this.hg=new x6(this);this.hg.Qp=null;this.hg.i=this.u;this.hg.connect(a)};
g.h.Xv=function(){return 0==this.g};
g.h.Yy=function(a){this.ng=null;Q6(this,a)};
g.h.Xy=function(){this.nf=null;this.Sb=new c6(this,this.l,"rpc",this.C);this.Sb.bh=null;this.Sb.Sp=0;var a=this.pu.clone();g.Vm(a,"RID","rpc");g.Vm(a,"SID",this.l);g.Vm(a,"CI",this.ko?"0":"1");g.Vm(a,"AID",this.li);H6(this,a);if(!g.Md||g.pd(10))g.Vm(a,"TYPE","xmlhttp"),f6(this.Sb,a,!0,this.rm,!1);else{g.Vm(a,"TYPE","html");var b=this.Sb,c=!!this.rm;b.Yh=3;b.Zf=h5(a.clone());q6(b,c)}};
g.h.Ty=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ie=a.Tj,this.yd==a&&3==this.g)if(7<this.Sg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Sb)if(this.Sb.Hi+3E3<this.yd.Hi)M6(this),this.Sb.cancel(),this.Sb=null;else break a;T6(this);i6(19)}}else this.Gw=c[1],0<this.Gw-this.li&&37500>c[2]&&this.ko&&0==this.Kh&&!this.Wg&&(this.Wg=s6((0,g.x)(this.lI,this),6E3));else V6(this,11)}else b!=dra.fO.g&&V6(this,11);else if(this.Sb==a&&
M6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.rm=e[2],e=e[3],null!=e?this.Sg=e:this.Sg=6,this.g=3,this.Tc&&this.Tc.Du(),this.pu=y6(this,this.Rk()?this.rm:null,this.Pp),R6(this)):"stop"==e[0]&&V6(this,7):3==this.g&&("stop"==e[0]?V6(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Cu(e),this.Kh=0)}}};
g.h.lI=function(){null!=this.Wg&&(this.Wg=null,this.Sb.cancel(),this.Sb=null,T6(this),i6(20))};
g.h.un=function(a){if(this.Sb==a){M6(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ie=a.Tj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.H)()-a.Hi,W6.dispatchEvent(new E6(W6,a.uh?a.uh.length:0,b,this.Sh)),K6(this),this.o.length=0):R6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ie)){if(d=1==b)this.yd||this.ng||1==this.g||2<=this.Sh?d=!1:(this.ng=s6((0,g.x)(this.Yy,this,a),S6(this,this.Sh)),this.Sh++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:V6(this,
5);break;case 4:V6(this,10);break;case 3:V6(this,6);break;case 7:V6(this,12);break;default:V6(this,2)}}};
g.h.KC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.IM=function(a){a?i6(2):(i6(1),U6(this,8))};
g.h.np=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new r5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.te=function(a){W6.dispatchEvent(new F6(W6,a))};
g.h.Rk=function(){return!(!g.Md||g.pd(10))};
g.h=X6.prototype;g.h.Du=function(){};
g.h.Cu=function(){};
g.h.Bu=function(){};
g.h.bp=function(){};
g.h.zv=function(){return{}};
g.h.isActive=function(){return!0};g.y(Y6,g.D);g.h=Y6.prototype;g.h.mL=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.bo(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.y(Z6,X6);g.h=Z6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Lf=function(a){return this.l.eh(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.qf(this.l),$6(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new C6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.li):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):a7(this)&&N6(this.g,c)};
g.h.Du=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)N6(this.g,a[b])}this.N("handlerOpened")};
g.h.Bu=function(a){var b=2==a&&401==this.g.Ie;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.bp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.zv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Cu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),J6(this.g)):this.N("handlerMessage",new vqa(a[0],a[1]))};
g.h.mM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};b7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
b7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
b7.prototype.u=function(a){a(Error("request timed out"))};var Bqa=(0,g.H)(),g7=null,k7=Array(50),j7=-1,l7=!1;g.y(m7,g.P);m7.prototype.Hd=function(){return this.g};
m7.prototype.contains=function(a){return!!H5(this.g,a)};
m7.prototype.get=function(a){return a?I5(this.g,a):null};
m7.prototype.info=function(a){i7(this.C,a)};g.t(o7,g.P);g.h=o7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.fB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Kp(this.za),this.za=NaN)};
g.h.U=function(){this.stop();g.P.prototype.U.call(this)};
g.h.fB=function(){this.za=NaN;this.g=g.Fq(c7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.jN,this),onError:(0,g.x)(this.iN,this),ie:(0,g.x)(this.kN,this)})};
g.h.jN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new A5(c))};
g.h.iN=function(a){this.g=null;a.status&&404==a.status?this.i>=w9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=w9[this.i],this.za=g.Ip((0,g.x)(this.fB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.kN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var w9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(q7,m7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.N("screenChange");!g.gt("yt-remote-lounge-token-expiration")&&r7(this);g.Kp(this.i);this.i=g.Ip((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);n7(this,a);s7(this,!1);this.N("screenChange");b(a);a.token||r7(this)};
g.h.remove=function(a,b){var c=p7(this);Dqa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.eo=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.Kp(this.i);q7.Xa.U.call(this)};
g.h.vD=function(a){p7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&i7(this.C,"Missed "+b+" lounge tokens.")};
g.h.uD=function(a){i7(this.C,"Requesting lounge tokens failed: "+a)};g.t(u7,g.P);g.h=u7.prototype;g.h.start=function(){var a=parseInt(g.gt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?x7(this):(this.o=(0,g.H)()+3E5,g.ft("yt-remote-fast-check-period",this.o),this.Yr())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){t7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!I5(a,d)},this);
w7(this,b)};
g.h.U=function(){g.Kp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.U.call(this)};
g.h.Yr=function(){g.Kp(this.l);this.l=NaN;this.i&&this.i.abort();var a=y7(this);if(u5(a)){var b=c7(this.u,"/pairing/get_screen_availability");this.i=d7(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.QK,this,a),(0,g.x)(this.PK,this))}else w7(this,{}),x7(this)};
g.h.QK=function(a,b){this.i=null;var c=g.Sb(y7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;w7(this,d);x7(this)}else this.Hb("Changing Screen set during request."),this.Yr()};
g.h.PK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;x7(this)};
g.h.Hb=function(a){i7("OnlineScreenService",a)};g.y(z7,m7);g.h=z7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.eo=function(a,b,c,d){this.l.contains(a)?this.l.eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.C,a),d(Error(a)))};
g.h.Hd=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.gB=function(){return(0,g.Yd)(this.Hd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.hB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(A7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.mN=function(a,b,c,d){g.Fq(c7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new A5(f.screen||{});if(!k.name||C7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);C7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(A7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ie:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);z7.Xa.U.call(this)};
g.h.DD=function(){D7(this);this.N("screenChange");this.i.update()};
z7.prototype.dispose=z7.prototype.dispose;g.y(F7,g.P);g.h=F7.prototype;g.h.wn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Kd=function(a){this.ea()||(a&&G7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){i7(this.P,a)};
g.h.jB=function(){return null};
g.h.rs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){G7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.rs("");F7.Xa.U.call(this)};g.y(I7,F7);g.h=I7.prototype;g.h.qs=function(a){if(this.g){if(this.g==a)return;G7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Hqa(this)};
g.h.ni=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Kd()},this),(0,g.x)(function(){this.Kd(Error("Failed to stop receiver app."))},this)):this.Kd(Error("Stopping cast device witout session."))};
g.h.rs=g.Ja;g.h.U=function(){this.info("disposeInternal");g.Kp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;I7.Xa.U.call(this)};
g.h.PL=function(a,b){if(!this.ea())if(b){var c=w5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":H7(this,c.screenId);break;default:G7(this,"Unknown youtube message: "+d)}}else G7(this,"Unable to parse message.")}else G7(this,"No data in message.")};
g.h.Pv=function(a,b,c,d){B7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(G7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ip((0,g.x)(this.Pv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.jB=function(){return this.g};
g.h.nN=function(a){this.ea()||a||(G7(this,"Cast session died."),this.Kd())};g.y(J7,F7);g.h=J7.prototype;g.h.qs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ni=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o?this.o.stop((0,g.x)(this.Kd,this,null),(0,g.x)(this.Kd,this,"Failed to stop DIAL device.")):this.Kd()};
g.h.U=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;J7.Xa.U.call(this)};
g.h.qN=function(a){this.ea()||a||(G7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Kd())};
g.h.gq=function(a){this.H=G5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,L7(this));a(b);K7(this)}else this.C=(0,g.x)(function(){g.Kp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,L7(this));a(c);K7(this)},this),this.A=g.Ip((0,g.x)(function(){this.C()},this),100)};
g.h.ZD=function(a,b,c){B7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.wn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.gq(b,c)},this),(0,g.x)(function(d){G7(this,"Failed to get DIAL screen: "+d);
this.gq(b,c)},this))};g.y(M7,F7);M7.prototype.stop=function(){this.Kd()};
M7.prototype.qs=g.Ja;M7.prototype.ni=function(){g.Kp(this.g);this.g=NaN;var a=I5(this.F.Hd(),this.i.label);a?this.wn(a):this.Kd(Error("No such screen"))};
M7.prototype.U=function(){g.Kp(this.g);this.g=NaN;M7.Xa.U.call(this)};g.y(N7,g.P);g.h=N7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.zK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Vy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.MI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),yqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.iB,this)),this.l=S7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",Q7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.vM=function(a,b){P7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)P7("Unsetting old screen status: "+this.g.i.friendlyName),R7(this,null)}if(a&&b){if(!this.g){c=I5(this.i.Hd(),a);if(!c){P7("setConnectedScreenStatus: Unknown screen.");return}var d=O7(this,c);d||(P7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
P7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);R7(this,new M7(this.i,d),!0)}this.g.rs(b)}else P7("setConnectedScreenStatus: no screen.")};
g.h.wM=function(a){this.ea()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ni(a):this.Hb("Setting connection data without a session")};
g.h.pN=function(){this.ea()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),R7(this,null)):P7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Vy,this),(0,g.x)(this.VK,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.iB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],e7);g.qf(this.g);N7.Xa.U.call(this)};
g.h.Hb=function(a){i7("Controller",a)};
g.h.Wy=function(a,b){this.g==a&&(b||R7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.vK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),P7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)P7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{P7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:R7(this,
new M7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:R7(this,new J7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:R7(this,new I7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.MI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return P7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);R7(this,new J7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.ZD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.gq,b))};
g.h.Vy=function(a){if(!this.ea()){P7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)P7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),R7(this,new I7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=I5(this.i.Hd(),c.label);d&&B5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(P7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new I7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Wy,this,this.g)),this.g.ni(null));this.g.qs(a)}}};
g.h.oN=function(){return this.g?this.g.jB():null};
g.h.VK=function(a){this.ea()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&R7(this,null))};
g.h.zK=function(a){P7("Receiver availability updated: "+a);if(!this.ea()){var b=Q7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;Q7(this)!=b&&this.N("yt-remote-cast2-availability-change",Q7(this))}};
g.h.iB=function(){this.ea()||(this.l=S7(this),P7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",Q7(this)))};
N7.prototype.setLaunchParams=N7.prototype.wM;N7.prototype.setConnectedScreenStatus=N7.prototype.vM;N7.prototype.stopSession=N7.prototype.pN;N7.prototype.getCastSession=N7.prototype.oN;N7.prototype.requestSession=N7.prototype.requestSession;N7.prototype.init=N7.prototype.init;N7.prototype.dispose=N7.prototype.dispose;var a8=[];i8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";j8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
i8.prototype.isAdPlaying=function(){return 1081==this.playerState};
i8.prototype.getDuration=function(){return this.u?this.D+k8(this):this.D};
i8.prototype.clone=function(){return new i8(o8(this))};g.t(r8,g.P);g.h=r8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,z8(this,"play")):x8(this,"play"),w8(this,1,m8(s8(this))),this.N("remotePlayerChange")):u8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,z8(this,"pause")):x8(this,"pause"),w8(this,2,m8(s8(this))),this.N("remotePlayerChange")):u8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=s8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,z8(this,"seekTo",{newTime:a}))}else x8(this,"seekTo",{newTime:a});w8(this,3,a);this.N("remotePlayerChange")}else u8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,z8(this,"stopVideo")):x8(this,"stopVideo");var a=s8(this);a.index=-1;a.videoId="";j8(a);v8(this,a);this.N("remotePlayerChange")}else u8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=s8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);x8(this,"setVolume",e)}c.muted=b;c.volume=a;v8(this,c)}else u8(this,g.Sa(this.setVolume,a,b))};
g.h.iA=function(a,b){if(1==this.g){var c=s8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));x8(this,"setSubtitlesTrack",d);v8(this,c)}else u8(this,g.Sa(this.iA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();x8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=s8(this);d.audioTrackId=c;v8(this,d)}else u8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=s8(this);c=c||0;var m={videoId:a,currentIndex:c};n8(l,a,c);g.Ea(b)&&(l8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));x8(this,"setPlaylist",m);d||v8(this,l)};
g.h.Dn=function(a,b){if(1==this.g){if(a&&b){var c=s8(this);n8(c,a,b);v8(this,c)}x8(this,"previous")}else u8(this,g.Sa(this.Dn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=s8(this);n8(c,a,b);v8(this,c)}x8(this,"next")}else u8(this,g.Sa(this.nextVideo,a,b))};
g.h.av=function(){1==this.g?x8(this,"dismissAutoplay"):u8(this,this.av)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.U=function(){t8(this);this.o=null;this.u.clear();q8(this,null);g.P.prototype.U.call(this)};
g.h.ct=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.sK=function(a,b){this.N(a,b)};
g.h.rI=function(a){if(!a)this.Ck(null),q8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=s8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,v8(this,b)}};
g.h.Ck=function(a){i7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),y8(this),this.N("remotePlayerChange")};
g.h.qI=function(a){a?(y8(this),this.N("remotePlayerChange")):this.Ck(null)};
g.h.Ls=function(){x8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.FI=function(){var a=e8();a&&q8(this,a)};
g.h.Hb=function(a){i7("CP",a)};g.t(A8,g.P);g.h=A8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;l8(this.Oa,m);this.o="UNSUPPORTED";B8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,P5())}else B8("Connecting without params"),this.g.connect({},a,P5());Oqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),C8(this,3));g.P.prototype.dispose.call(this)};
g.h.U=function(){D8(this);F8(this);E8(this);g.Kp(this.C);this.C=NaN;g.Kp(this.D);this.D=NaN;this.l=null;g.Or(this.P);this.P.length=0;this.g.dispose();g.P.prototype.U.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.oD=function(){this.Oh(2)};
g.h.vI=function(){B8("Channel opened");this.I&&(this.I=!1,E8(this),this.H=g.Ip((0,g.x)(function(){B8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
pqa(wqa(this.g),this.M)};
g.h.sI=function(){B8("Channel closed");isNaN(this.u)?S5(!0):S5();this.dispose()};
g.h.tI=function(a){S5();isNaN(this.Hj())?(B8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,B8("Channel error: "+a+" with reconnection in "+this.Hj()+" ms"),C8(this,2))};
g.h.uI=function(a){a.params?B8("Received: action="+a.action+", params="+g.Kg(a.params)):B8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=w5(a.params.devices);this.i=(0,g.B)(a,function(c){return new z5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
I8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
I8(this,!1);break;case "remoteConnected":var b=new z5(w5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||eqa(this.i,b);
break;case "remoteDisconnected":b=new z5(w5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":J8(this,a);break;case "nowPlaying":Rqa(this,a);break;case "onStateChange":K8(this,a);break;case "onAdStateChange":Sqa(this,a);break;case "onVolumeChanged":Tqa(this,a);break;case "onSubtitlesTrackChanged":Qqa(this,a);break;case "nowAutoplaying":Uqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Vqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:B8("Unrecognized action: "+a.action)}};
g.h.jM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&G8(this,"getNowPlaying")}};
g.h.eD=function(){var a=3;this.ea()||(a=0,isNaN(this.Hj())?a7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Oh=function(a){B8("Disconnecting with "+a);D8(this);this.N("beforeDisconnect",a);1==a&&S5();$6(this.g,a);this.dispose()};
g.h.dD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),n8(a,this.l,a.index));return o8(a)};
g.h.xM=function(a){var b=new i8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Kp(this.C),this.C=g.Ip((0,g.x)(this.jM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&m8(this.Oa)==m8(b)&&g.Kg(this.Oa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Mv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Hj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.WC=function(){return this.o||"UNSUPPORTED"};
g.h.XC=function(){return this.A||""};
g.h.hN=function(){if(!isNaN(this.Hj())){var a=this.g.i;g.co(a.g);a.start()}};
g.h.qM=function(a,b){G8(this,a,b);H8(this)};
A8.prototype.subscribe=A8.prototype.subscribe;A8.prototype.unsubscribeByKey=A8.prototype.Lf;A8.prototype.getProxyState=A8.prototype.eD;A8.prototype.disconnect=A8.prototype.Oh;A8.prototype.getPlayerContextData=A8.prototype.dD;A8.prototype.setPlayerContextData=A8.prototype.xM;A8.prototype.getOtherConnectedRemoteId=A8.prototype.Mv;A8.prototype.getReconnectTimeout=A8.prototype.Hj;A8.prototype.getAutoplayMode=A8.prototype.WC;A8.prototype.getAutoplayVideoId=A8.prototype.XC;A8.prototype.reconnect=A8.prototype.hN;
A8.prototype.sendMessage=A8.prototype.qM;g.t(L8,m7);g.h=L8.prototype;g.h.Hd=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;m7.prototype.U.call(this)};
g.h.lN=function(){this.N("screenChange")};
g.h.WJ=function(){this.N("onlineScreenChange")};
z7.prototype.$_st=z7.prototype.start;z7.prototype.$_gspc=z7.prototype.mN;z7.prototype.$_gsppc=z7.prototype.hB;z7.prototype.$_c=z7.prototype.contains;z7.prototype.$_g=z7.prototype.get;z7.prototype.$_a=z7.prototype.add;z7.prototype.$_un=z7.prototype.eo;z7.prototype.$_r=z7.prototype.remove;z7.prototype.$_gs=z7.prototype.Hd;z7.prototype.$_gos=z7.prototype.gB;z7.prototype.$_s=z7.prototype.subscribe;z7.prototype.$_ubk=z7.prototype.Lf;var g9=null,f9=!1,M8=null,N8=null,c9=null,R8=[];g.t(h9,g.D);g.h=h9.prototype;
g.h.U=function(){g.D.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Sy,this);this.g.unsubscribe("remotePlayerChange",this.Ek,this);this.g.unsubscribe("remoteQueueChange",this.xn,this);this.g.unsubscribe("autoplayUpNext",this.vy,this);this.g.unsubscribe("previousNextChange",this.Py,this);this.g.unsubscribe("nowAutoplaying",this.Ly,this);this.g.unsubscribe("autoplayDismissed",this.uy,this);this.g=this.u=null};
g.h.qx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!s8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==s8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Pj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.pI=function(a){this.I.kD(a)};
g.h.SM=function(a){this.qx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.vA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||m9(this,a)};
g.h.Hy=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.Ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=s8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Ek,this)}};
g.h.qJ=function(){g.Yb(this.C)||o9(this,this.C);this.D=!1};
g.h.Sy=function(a,b){this.A.stop();2==b&&this.uA()};
g.h.Ek=function(){if(l9(this)){this.o.stop();var a=s8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Km=1;break;case 1082:case 1083:this.u.Km=0;break;default:this.u.Km=-1}switch(a.playerState){case 1081:case 1:j9(this,new g.iC(8));this.tA();break;case 1085:case 3:j9(this,new g.iC(9));break;case 1083:case 0:j9(this,new g.iC(2));this.H.stop();i9(this,this.i.getVideoData().lengthSeconds);break;case 1084:j9(this,new g.iC(4));break;case 2:j9(this,new g.iC(4));i9(this,m8(a));
break;case -1:j9(this,new g.iC(64));break;case -1E3:j9(this,new g.iC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=s8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,o9(this,a));a=s8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.TA()}else k9(this)};
g.h.Py=function(){this.i.N("mdxpreviousnextchange")};
g.h.xn=function(){l9(this)||k9(this)};
g.h.qC=function(){this.g.av()};
g.h.vy=function(a){a&&(a=g.Fq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.xL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.xL=function(a,b){var c=new g.VA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Ly=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.uy=function(){this.i.N("mdxautoplaycanceled")};
g.h.MF=function(a,b){-1==s8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.TA=function(){if(l9(this)){var a=s8(this.g);this.l.Ka(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Hy)}};
g.h.tA=function(){this.o.stop();if(!this.g.ea()){var a=s8(this.g);1==a.playerState&&j9(this,new g.iC(8));i9(this,m8(a));this.o.start()}};
g.h.uA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(q9,g.W);q9.prototype.o=function(){y5("mdx-privacy-popup-cancel");this.l.hide()};
q9.prototype.A=function(){y5("mdx-privacy-popup-confirm");this.l.hide()};g.t(s9,g.W);s9.prototype.u=function(a){r9(this,a.state)};g.t(t9,g.GT);t9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.HT(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.A=function(a){return a.key};
t9.prototype.re=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
t9.prototype.Ic=function(a){g.GT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(u9,g.zK);g.h=u9.prototype;
g.h.create=function(){$qa(g.Fy(g.X(this.player)));this.o.push(g.Pp("yt-remote-before-disconnect",this.mI,this));this.o.push(g.Pp("yt-remote-connection-change",this.AK,this));this.o.push(g.Pp("yt-remote-receiver-availability-change",this.Qy,this));this.o.push(g.Pp("yt-remote-auto-connect",this.yK,this));this.o.push(g.Pp("yt-remote-receiver-resumed",this.xK,this));this.o.push(g.Pp("mdx-privacy-popup-confirm",this.ZL,this));this.o.push(g.Pp("mdx-privacy-popup-cancel",this.YL,this));this.Qy()};
g.h.load=function(){this.player.cancelPlayback();g.zK.prototype.load.call(this);this.u=new h9(this,this.player,this.g);var a=(a=e9())?a.currentTime:0;var b=b9()?new r8(X8(),void 0):null;0==a&&b&&(a=m8(s8(b)));0!=a&&this.Kc(a);p9(this,this.mk,this.mk);g.GX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.zK.prototype.unload.call(this);g.GX(this.player.app,5)};
g.h.U=function(){g.Qp(this.o);g.zK.prototype.U.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.qx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Km};
g.h.gD=function(){return this.loaded?this.u.suggestion:null};
g.h.Je=function(){return this.g?s8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?s8(this.g).hasNext:!1};
g.h.Kc=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=s8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+k8(a):a.l,isAtLiveHead:1>=(a.u?a.i+k8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+k8(a):a.i,seekableStart:0<a.o?a.o+
k8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Dn=function(){this.g&&this.g.Dn()};
g.h.mI=function(a){1==a&&(this.C=this.g?s8(this.g):null)};
g.h.AK=function(){var a=b9()?new r8(X8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,m8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Qy=function(){this.A=[this.i].concat(ara());var a=Y8()||this.i;v9(this,a);this.player.la("onMdxReceiversChange")};
g.h.yK=function(){var a=Y8();v9(this,a)};
g.h.xK=function(){this.l=Y8()};
g.h.ZL=function(){this.D=!0;f9=!1;g9&&$8(g9,1);g9=null};
g.h.YL=function(){this.D=!1;v9(this,this.i);this.l=this.i;f9=!1;g9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g8():v9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&g8(),!0):!1}};
g.h.Ls=function(){this.g.Ls()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.XU.remote=u9;})(_yt_player);
